name: feedHeal
author: Psycofeu
api: 5.0.0
version: 1.0.0
description: §9https://discord.gg/vanillaMCBE
website: "§ghttps://github.com/Psycofeu"
main: psycofeu\feedheal\Main

permissions:
  feed.use:
    default: op
  heal.use:
    default: op
